---
name: "samples.csv"
chunksize: 1000000
compression: true
usecols:
  - id
  - device_id
  - timestamp
  - app_version
  - database_version
  - battery_level
  - battery_state
  - memory_active
  - memory_inactive
  - memory_free
  - network_status
  - screen_brightness
  - screen_on
  - timezone
  - country_code
  - triggered_by
parse_dates:
  - timestamp
plugins:
  before:
    - dropna
    - date_filtering
  after:
    - clean_samples